-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAwJp/PbsX+D04nw3Vg0a6iLVfXApmqEcWM9mrnqjvDSgCgYIKoZIzj0DAQehRANCAARbe1KlmxrqQORB2Yp5QtxTBPMi4qmcV02P1sGc/nbFV8r+UXklHZfm6jV2ZtQxZ/CfkPOjSIbwzeJkSHpcMuV5
-----END PRIVATE KEY-----